package com.soch.uam.dto;
// Generated Sep 3, 2016 1:45:48 PM by Hibernate Tools 4.3.4.Final

/**
 * ConfigTb generated by hbm2java
 */
public class ConfigDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2168685399785002714L;
	
	
	private String configName;
	private String configValue;

	public ConfigDTO() {
	}

	public ConfigDTO(String configName) {
		this.configName = configName;
	}

	public ConfigDTO(String configName, String configValue) {
		this.configName = configName;
		this.configValue = configValue;
	}

	public String getConfigName() {
		return this.configName;
	}

	public void setConfigName(String configName) {
		this.configName = configName;
	}

	public String getConfigValue() {
		return this.configValue;
	}

	public void setConfigValue(String configValue) {
		this.configValue = configValue;
	}

}
